# Generated by Django 2.2 on 2019-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=4)),
                ('key_words', models.CharField(max_length=100)),
                ('previous_message_id', models.IntegerField()),
            ],
        ),
    ]
