# Generated by Django 2.2 on 2019-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='previous_message_id',
            field=models.IntegerField(null=True),
        ),
    ]
